### ISSUE TITLE
Error: argument Zlatent.train must be a double vector

### ISSUE THREAD

**Issue by jeyabbalas** [cran/bartBMA#1]
Hi,

I was exploring bartBMA in R for modeling gene expression datasets (from NCBI's Gene Expression Omnibus) for a classification task. The predictor variables are all continuous floating point values (as I understand the package currently does not support categorical variables). The outcome variable is binary. I have attached a sample mini version of the dataset.
[GSE66360.txt](https://github.com/cran/bartBMA/files/4373375/GSE66360.txt)

I am loading and training the dataset as follows—
```
train <- read.csv(file = './GSE66360.txt')
X_train <- train[,c("X1","X2")]
X_train <- data.matrix(X_train)
y_train <- train['Y']
y_train <- ifelse(y_train==1,1,0)

bart_bma_trial <- probit_bartBMA(x.train=X_train,y.train=y_train)
```
This call throws the following error—
```
Error in probit_bartBMA.default(x.train = X_train, y.train = y_train) : 
  argument Zlatent.train must be a double vector
```

I don't understand the error statement. 

I was able to run the example in the manual just fine. The datatypes of my input is the same as the manual.

Please advise. Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by jeyabbalas** [comment]
Oh, sorry about that. Thanks!
